### ISSUE TITLE
Support for multiple routes

### ISSUE THREAD

**Issue by qanx** [concourse/autopilot#1]
We were playing around with this plugin and noticed that for our apps with multiple routes only one route is preserved when we re-push our app with `cf zero-downtime-push`. Could you please add the ability to handle multiple routes? Thanks!

**Comment by drnic** [comment]
Is there a way to specify routes in your `manifest.yml`? I can't see anything in http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html

**Comment by drnic** [comment]
I don't see anything https://github.com/cloudfoundry/cli/blob/master/cf/manifest/manifest.go#L130-L170

**Comment by vito** [comment]
Opened an issue upstream in the CLI: https://github.com/cloudfoundry/cli/issues/358

**Comment by vito** [comment]
The latest CF CLI now supports setting multiple domains and multiple host names in the manifest.

Example usage: https://github.com/concourse/concourse/blob/master/docs/manifest.yml#L5

We actually continuously update the CF CLI so there's not anything for us to do as long as these kinds of things are fixed upstream. I'm going to go ahead and close this issue; if the current state of things isn't what you want would you mind opening an issue upstream instead?
