### ISSUE TITLE
Delete the renamed app

### ISSUE THREAD

**Issue by yookore** [concourse/autopilot#12]
autopilot should delete the renamed app after successful completion of the hot deployment. 

I see this when I cf zero-downtime-push uas -f manifest.yml`
```
FAILED
Server error, status code: 400, error code: 100002, message: The app name is taken: uas-venerable
error: Error executing cli core command
```
Happens because autopilot still keeps the old renamed app. Is there a flag to force it not to keep the renamed app?

**Comment by xoebus** [comment]
It should delete it if everything worked correctly. Make sure that your original deploy was successful.

Please feel free to re-open this if this is not the case.
