### ISSUE TITLE
Failure when app does not already exist

### ISSUE THREAD

**Issue by RochesterinNYC** [concourse/autopilot#14]
Autopilot seems to assume that your app already exists. If you try to run it with an app that does not already exist, the following error occurs:

```
$ cf zero-downtime-push new-app -f manifest.yml -p .
FAILED
App new-app not found
error: Error executing cli core command
```

Unsure if this is actually intended behavior (considering not having the app exist might be considered a fringe case) or a bug.

- James && @jchesterpivotal

**Comment by xoebus** [comment]
Should be fixed now on `master`.
