### ISSUE TITLE
Changes route before checking parameters

### ISSUE THREAD

**Issue by teancom** [concourse/autopilot#2]
If you run `cf zero-downtime-push appname` without passing in a manifest.yml, it first renames the old app to training-venerable, and *then* checks to see that you forgot to pass in a manifest and dies. At that point, re-running the same command but with `-f manifest.yml` appended doesn't work, and confusion reigns.

Thank you!

**Comment by xoebus** [comment]
@teancom Thanks for reporting! I'll file a bug in our tracker.
