### ISSUE TITLE
unable to set health check to none

### ISSUE THREAD

**Issue by dlutsch** [concourse/autopilot#21]
with the normal cf push I also pass the `--health-check-type none` parameter on my worker applications that contain no routes. This option does not seem to exist in autopilot yet. The result is that any pushed applications will fail to start due to failing the default health check

**Comment by xoebus** [comment]
Is it possible to set this in the manifest?

**Comment by afeld** [comment]
@dlutsch Would [`no-route`](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#no-route) work?

**Comment by xoebus** [comment]
We use `no-route` in one of our internal applications and it disables the port health check. I'm going to close this for now but if that doesn't work then feel free to re-open.
