### ISSUE TITLE
Interrupted deploy breaks subsequent zero downtime deploys

### ISSUE THREAD

**Issue by danfinnie** [concourse/autopilot#4]
When a deploy dies, the venerable app persists in CF.  When you deploy again, the deploy fails with this error:

```
+ cf zero-downtime-push APPNAME -f manifest.yml -p $WORKSPACE
Renaming app APPNAME to APPNAME-venerable in org ORG / space acceptance as ********...
FAILED
Server error, status code: 400, error code: 100002, message: The app name is taken: APPNAME-venerable
```

In this scenario, we go into CF and delete the venerable instance manually.  Maybe the plugin could do this for us (this wouldn't be a zero downtime deploy but neither is our current solution).  Alternately, the app could push to the non-venerable instance, change the route, and then delete the venerable instance.

@mikfreedman @mbildner

**Comment by mikfreedman** [comment]
👊

**Comment by xoebus** [comment]
I've pushed a half fix for this that should some of the problems here.

Unfortunately, this is really hard. The `cf push` can leave the system in countless states that all have different actions required to undo them. Also, these undo actions can then fail and everything gets into a mess.

Another consideration is that none of these undo actions can ever cause the application to have downtime. This would be a critical failing on the part of the plugin.

I'll re-open this while I have a think about if there's a simple way to perform safe reverts.

**Comment by thinkalike-dev** [comment]
Same issue for us. One thing you might do if cf push fails is deleting the non venerable app and renaming venerable back to non venerable. In this case, the subsequent zero-downtime-deploys will be possible after the cf push issue is resolved. 

Worth implementing ?

**Comment by RochesterinNYC** [comment]
Hi! Wondering what the status of this issue is or what the Concourse team is thinking regarding fixing this behavior. We are interested in the autopilot plugin primarily because of the 'auto' aspect.

Our goal is to retire a custom blue/green tooling which drives the CF CLI. That code wraps a lot of 'classic' CF CLI commands. New code to wrap a different command isn't a win over sticking with what we have, unfortunately.

- James and @jchesterpivotal

**Comment by xoebus** [comment]
I'd be happy to review any PRs that handle rollback. I don't think we have the bandwidth to look at this ourselves right now.

**Comment by jchesterpivotal** [comment]
I'm afraid we don't either. :(

**Comment by xoebus** [comment]
Should be fixed now on `master`.
